version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: motor_claim_web_app
    ports:
      - "8501:8501"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GEMINI_MODEL_NAME=gemini-1.5-pro
      - GEMINI_TEMPERATURE=0.2
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./data:/app/data
      - ./docs:/app/docs
    depends_on:
      - mlflow

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.15.0
    container_name: mlflow_tracking_server
    ports:
      - "5000:5000"
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlruns --host 0.0.0.0 --port 5000
    volumes:
      - ./mlruns:/mlruns
